const pkmnTheme = "I want to be the very best Like no one ever was To catch them is my real test To train them is my cause I will travel across the land Searching far and wide Each Pokemon to understand The power thats inside Pokemon Gotta catch em all Its you and me I know its my destiny Pokemon Oh youre my best friend In a world we must defend Pokemon Gotta catch em all A heart so true Our courage will pull us through You teach me and Ill teach you Pokemon Gotta catch em all Gotta catch em all Every challenge along the way With courage I will face I will battle every day To claim my rightful place Come with me the time is right Theres no better team Arm in arm well win the fight Its always been our dream Pokemon Gotta catch em all Its you and me I know its my destiny Pokemon Oh youre my best friend In a world we must defend Pokemon Gotta catch em all A heart so true Our courage will pull us through You teach me and Ill teach you Pokemon Gotta catch em all Gotta catch em all Gotta catch em all Gotta catch em all Gotta catch em all Pokemon Gotta catch em all Its you and me I know its my destiny Pokemon Oh youre my best friend In a world we must defend Pokemon Gotta catch em all A heart so true Our courage will pull us through You teach me and Ill teach you Pokemon Gotta catch em all Gotta catch em all Pokemon abcdefg hijklmnop qrs tuv wx y and z";

const bohemianRhapsody = "Is this the real life Is this just fantasy Caught in a landslide, no escape from reality Open your eyes, look up to the skies and see Im just a poor boy, I need no sympathy Because Im easy come, easy go, little high, little low Any way the wind blows doesnt really matter to me, to me Mama, just killed a man Put a gun against his head, pulled my trigger, now hes dead Mama, life had just begun But now Ive gone and thrown it all away Mama, ooh, didnt mean to make you cry If Im not back again this time tomorrow Carry on, carry on as if nothing really matters Too late, my time has come Sends shivers down my spine, bodys aching all the time Goodbye, everybody, Ive got to go Gotta leave you all behind and face the truth Mama, ooh Any way the wind blows I dont wanna die I sometimes wish Id never been born at all I see a little silhouetto of a man Scaramouche, Scaramouche, will you do the Fandango Thunderbolt and lightning, very, very frightening me Galileo Galileo, Galileo Galileo, Galileo Figaro magnifico But Im just a poor boy, nobody loves me Hes just a poor boy from a poor family Spare him his life from this monstrosity Easy come, easy go, will you let me go Bismillah No, we will not let you go Let him go Bismillah We will not let you go Let him go Bismillah We will not let you go Let me go Will not let you go Let me go Will not let you go Never, never, never, never let me go Ah No, no, no, no, no, no, no Oh, mamma mia, mamma mia Mamma mia, let me go Beelzebub has a devil put aside for me, for me, for me So you think you can stone me and spit in my eye So you think you can love me and leave me to die Oh, baby, cant do this to me, baby Just gotta get out, just gotta get right outta here Ooh Ooh, yeah, ooh, yeah Nothing really matters, anyone can see Nothing really matters Nothing really matters to me Any way the wind blows abcdefg hijklmnop qrs tuv wx y and z";

const toBe = "To be, or not to be, that is the question Whether tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take arms against a sea of troubles And by opposing end them. To die to sleep, No more and by a sleep to say we end The heartache and the thousand natural shocks That flesh is heir to tis a consummation Devoutly to be wishd. To die, to sleep To sleep, perchance to dreamay, theres the rub For in that sleep of death what dreams may come, When we have shuffled off this mortal coil, Must give us pause theres the respect That makes calamity of so long life. For who would bear the whips and scorns of time, The oppressors wrong, the proud mans contumely, The pangs of disprizd love, the laws delay, The insolence of office, and the spurns That patient merit of the unworthy takes, When he himself might his quietus make With a bare bodkin ? Who would fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered country, from whose bourn No traveller returns, puzzles the will, And makes us rather bear those ills we have Than fly to others that we know not of ? Thus conscience does make cowards of us all, And thus the native hue of resolution Is sicklied over with the pale cast of thought, And enterprises of great pitch and moment With this regard their currents turn awry And lose the name of action.";

const avatar = "Water. Earth. Fire. Air. Long ago, the four nations lived together in harmony. Then, everything changed when the Fire Nation attacked. Only the Avatar, master of all four elements, could stop them, but when the world needed him most, he vanished. A hundred years passed and my brother and I discovered the new Avatar, an airbender named Aang, and although his airbending skills are great, he has a lot to learn before he is ready to save anyone. But I believe Aang can save the world.";

export const endlessText = [
  pkmnTheme,
  bohemianRhapsody,
  toBe,
  avatar,
];